production:
  report_host: "auk-pddrop1.mcom.local"
  report_path: 'Drop/TEDrop/reports/automation'
  mount_point: "/raw" # relative to public folder
  username: 'SVC_testuser'
  password: 'Automation_!'

development:
  report_host: "auk-pddrop1.mcom.local"
  report_path: 'Drop/TEDrop/reports/mock'
  mount_point: "/raw" # relative to public folder
  username: 'SVC_testuser'
  password: 'Automation_!'

test:
  report_host: http://testeng-1-w1.mcom.local/
