# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8f2d7d48a8b1d31dd2b15093ab3995deb22afd044cfe2d9d336e89a9fc28597e213ae86fc44d5903a378e2eb34d249d27cf0ae5608ce8e9e08b8b2f12ce4c25

test:
  secret_key_base: 32aa370b23c34b3569ea5ba6ae5fd957297824b9a27fbbe1c4026d97a05b9cb6e22b40b465e67a63be5b07505d2b8c8d000e90633ff0cbf58d5d89a6d8661cfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
