production:
  report_host: <%= ENV["REPORT_HOST"] %>
  report_path: <%= ENV["REPORT_PATH"] %>
  mount_point: <%= ENV["MOUNT_POINT"] %>
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>

development:
  report_host: <%= ENV["REPORT_HOST"] %>
  report_path: <%= ENV["REPORT_PATH"] %>
  mount_point: <%= ENV["MOUNT_POINT"] %>
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>

test:
  report_host: http://testeng-1-w1.mcom.local/
